# This is a basic workflow to help you get started with Actions

name: ğŸ–¥ï¸ Compress Json Schemas
on:
  push:
    branches:
      - main
    paths:
      - "**/*.json"

  workflow_dispatch:

concurrency:
  group: compress-schemas
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    name: ğŸ–¥ï¸ Compress Schemas
    steps:
      - name: ğŸ“¦ Checkout Repository
        uses: actions/checkout@v5

      - name: âŒ› Get Time
        id: time
        uses: nanzm/get-time-action@v2.0
        with:
          timeZone: 8
          format: "YYYY-MM-DD"

      - name: ğŸ’¾ Compress Json
        uses: DaanV2/Json-Schema-Action-Compression@v3.6
        with:
          specificationFile: "source/compress_specification.json"

      - name: âœï¸ Commit and Create PR
        uses: peter-evans/create-pull-request@v7
        with:
          branch: auto/update-schemas
          commit-message: "auto: generated json schemas ${{ steps.time.outputs.time }}"
          title: "Automated JSON schema update"
          body: "This PR updates the generated JSON schemas."
